import { StyleSheet } from "react-native";

import { Fonts } from "@/constants/theme";

export const readerScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  content: {
    paddingTop: 24,
    gap: 20,
    userSelect: "none",
  },
  headerStrip: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  heroCopy: {
    flex: 1,
    gap: 4,
  },
  chapterEyebrow: {
    fontFamily: Fonts.rounded,
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  chapterTitle: {
    fontFamily: Fonts.rounded,
    fontSize: 30,
    lineHeight: 36,
  },
  bookTitle: {
    fontFamily: Fonts.serif,
    fontSize: 14,
    lineHeight: 20,
  },
  headerActionButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  headerActionText: {
    fontFamily: Fonts.rounded,
    fontSize: 13,
    lineHeight: 16,
  },
  readingPanel: {
    userSelect: "none",
  },
  paragraphBlock: {
    borderRadius: 12,
  },
  paragraphRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-end",
    rowGap: 12,
  },
  inlineUnit: {
    borderRadius: 8,
    justifyContent: "flex-end",
    userSelect: "none",
  },
  inlineUnitWithSpacing: {
    marginHorizontal: 4,
  },
  inlineUnitContent: {
    position: "relative",
  },
  rubyUnit: {
    alignItems: "center",
    gap: 1,
    minHeight: 42,
  },
  rubyText: {
    fontFamily: Fonts.rounded,
    fontSize: 11,
    lineHeight: 13,
  },
  baseText: {
    fontFamily: Fonts.serif,
    fontSize: 26,
    lineHeight: 38,
  },
  baseTokenWrap: {
    position: "relative",
  },
  tokenNoteUnderline: {
    position: "absolute",
    left: 1,
    right: 1,
    bottom: -4,
    height: 1.5,
    borderRadius: 999,
    backgroundColor: "#C77F2F",
  },
  sentenceNoteUnderline: {
    position: "absolute",
    left: -2,
    right: -2,
    bottom: -0.5,
    height: 2.5,
    backgroundColor: "#C77F2F",
  },
  sentenceNoteUnderlineStart: {
    left: 0,
    borderTopLeftRadius: 999,
    borderBottomLeftRadius: 999,
  },
  sentenceNoteUnderlineEnd: {
    right: 0,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    backgroundColor: "#C77F2F",
  },
  focusReturnButton: {
    minWidth: 72,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  sheetActionText: {
    fontFamily: Fonts.rounded,
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
  },
  settingsModalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  settingsSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
    gap: 14,
  },
  noteComposerSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    gap: 14,
    maxHeight: "82%",
  },
  settingsSheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  settingsSheetTitle: {
    fontFamily: Fonts.rounded,
    fontSize: 26,
    lineHeight: 32,
  },
  settingsPanel: {
    gap: 12,
  },
  settingsRow: {
    gap: 8,
  },
  settingsLabel: {
    fontFamily: Fonts.rounded,
    fontSize: 12,
    lineHeight: 16,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  choiceChipText: {
    fontFamily: Fonts.rounded,
    fontSize: 13,
    lineHeight: 16,
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepperButton: {
    minWidth: 54,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
  },
  stepperText: {
    fontFamily: Fonts.rounded,
    fontSize: 13,
    lineHeight: 16,
  },
  stepperValue: {
    minWidth: 36,
    textAlign: "center",
    fontFamily: Fonts.rounded,
    fontSize: 14,
    lineHeight: 18,
  },
  modalRoot: {
    flex: 1,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  lookupModal: {
    position: "absolute",
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  modalHeaderCopy: {
    flex: 1,
    gap: 2,
    paddingRight: 8,
  },
  modalHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  modalTitle: {
    fontFamily: Fonts.rounded,
    fontSize: 18,
    lineHeight: 24,
  },
  modalIconButton: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  modalMeta: {
    fontSize: 13,
    lineHeight: 18,
  },
  modalHandle: {
    alignItems: "center",
    gap: 4,
    justifyContent: "center",
    minHeight: 24,
    minWidth: 28,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  modalHandleBar: {
    borderRadius: 999,
    height: 3,
    width: 18,
    opacity: 0.65,
  },
  modalBody: {
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 42,
    paddingTop: 14,
  },
  rubyLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  legendItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  legendDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  legendText: {
    fontSize: 12,
    lineHeight: 16,
  },
  sentenceText: {
    fontFamily: Fonts.serif,
    fontSize: 18,
    lineHeight: 29,
  },
  entryBlock: {
    gap: 8,
  },
  entryKey: {
    fontFamily: Fonts.rounded,
    fontSize: 15,
    lineHeight: 21,
  },
  entryDefinition: {
    fontFamily: Fonts.serif,
    fontSize: 15,
    lineHeight: 25,
  },
  emptyStateText: {
    fontSize: 14,
    lineHeight: 20,
  },
  notesSection: {
    gap: 10,
  },
  notesSectionTitle: {
    fontFamily: Fonts.rounded,
    fontSize: 15,
    lineHeight: 20,
  },
  noteCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    gap: 6,
  },
  noteTitle: {
    fontFamily: Fonts.rounded,
    fontSize: 14,
    lineHeight: 18,
  },
  noteBody: {
    fontSize: 14,
    lineHeight: 22,
  },
  noteMeta: {
    fontSize: 12,
    lineHeight: 16,
  },
  noteComposerBody: {
    flexShrink: 1,
    gap: 14,
  },
  noteContextBlock: {
    gap: 8,
  },
  noteSelectionText: {
    fontFamily: Fonts.serif,
    fontSize: 18,
    lineHeight: 28,
  },
  noteDictionaryKey: {
    fontFamily: Fonts.rounded,
    fontSize: 14,
    lineHeight: 19,
    marginBottom: 10,
  },
  noteDictionaryText: {
    fontSize: 14,
    lineHeight: 22,
  },
  noteDictionaryReadonlyInput: {
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontFamily: Fonts.serif,
    textAlignVertical: "top",
  },
  noteDictionaryPanel: {
    borderRadius: 18,
    borderWidth: 1,
    maxHeight: 180,
    overflow: "hidden",
    borderStyle: "dashed",
  },
  noteDictionaryScroll: {
    flexGrow: 0,
  },
  noteDictionaryScrollContent: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  noteInput: {
    minHeight: 148,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: Fonts.serif,
    fontSize: 15,
    lineHeight: 24,
    textAlignVertical: "top",
  },
  noteAiHint: {
    fontSize: 13,
    lineHeight: 20,
  },
  noteSaveButton: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  noteFooterActions: {
    flexDirection: "row",
    gap: 10,
  },
  noteSecondaryButton: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  resizeHandle: {
    position: "absolute",
    right: 10,
    bottom: 10,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    height: 28,
    width: 28,
  },
  resizeGrip: {
    height: 18,
    width: 18,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderBottomRightRadius: 14,
  },
  resizeGripSecondary: {
    position: "absolute",
    right: 2,
    bottom: 2,
    height: 10,
    width: 10,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderBottomRightRadius: 9,
  },
  readingViewport: {
    overflow: "hidden",
  },
  readingViewportScroll: {
    paddingBottom: 36,
  },
});
